name: Build and Deploy to Local Ubuntu using Docker

on:
  push:
    branches:
      - feat/TK-156-뱅킹-상세-예외처리  # 원하는 브랜치로 설정

env:
  DOCKER_IMAGE_NAME: with-bee-dev  # Docker 이미지 이름
  LOCAL_UBUNTU_HOST: 192.168.0.39  # 로컬 우분투 IP 주소
  LOCAL_UBUNTU_SSH_USER: team05  # 로컬 우분투 사용자 이름
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}  # SSH 접속 비밀번호 (GitHub Secrets에서 설정)
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
  DOCKER_HUB: ${{ secrets.DOCKER_USERNAME }}/withbee-dev  # Docker Hub 이미지 이름
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: 1234
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

jobs:
  # 1단계: 빌드
# 1단계: 빌드 및 테스트 (Gradle 빌드)
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      # Gradle 빌드 (JAR 파일 생성)
      - name: Build with Gradle Wrapper
        run: ./gradlew build


  # 2단계: Docker 이미지 빌드 및 Docker Hub 푸시
  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: build  # build job이 성공적으로 끝난 후 실행됨
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/withbee-dev:latest

      - name: Login to Docker Hub using Access Token
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/withbee-dev:latest

  # 3단계: 로컬 Ubuntu에 Docker 배포
  deploy-to-ubuntu:
    runs-on: ubuntu-latest
    needs: build-and-push-docker  # Docker 빌드와 푸시가 성공해야 실행됨
    steps:
      - name: Deploy to Local Ubuntu
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LOCAL_UBUNTU_HOST }}  # 로컬 우분투 IP 주소
          username: ${{ secrets.LOCAL_UBUNTU_SSH_USER }}  # 로컬 우분투 사용자 이름
          password: ${{ secrets.SSH_PASSWORD }}  # SSH 비밀번호
          script: |
            # 로컬 우분투에서 기존 컨테이너가 있을 경우 제거
            CONTAINER_ID=$(sudo docker ps -q --filter "publish=80-8080")
            
            if [ ! -z "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi
            
            # Docker Hub에서 새 이미지 pull
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/withbee-dev:latest
            
            # 새로운 컨테이너로 실행
            sudo docker run --name with-bee-dev -d -p 80:8080 -e TZ=Asia/Seoul \
            -e SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/withbee?serverTimezone=UTC&characterEncoding=UTF-8 \
            -e SPRING_DATASOURCE_USERNAME=root -e SPRING_DATASOURCE_PASSWORD=1234 \
            ${{ secrets.DOCKER_USERNAME }}/withbee-dev:latest  # 로컬에서는 MySQL 주소를 localhost로 설정
